---
driver:
  name: proxy
  host: localhost
  reset_command: "exit 0"
  port: 5985
  username: <%= ENV["machine_user"] %>
  password: <%= ENV["machine_pass"] %>

verifier:
  name: inspec

provisioner:
  name: chef_zero
  deprecations_as_errors: true

platforms:
  - name: windows-2012R2

suites:
  - name: apache2_config
    run_list:
      - recipe[test::apache2_config]
  - name: 64bit_apache
    run_list:
      - recipe[test::default]
    attributes:
      apache:
        windows:
          x86_override: false
          extras:
            - vhosts
            - ssl
  - name: x86_apache
    run_list:
      - recipe[test::default]
    attributes:
      apache:
        windows:
          x86_override: true
          extras:
            - vhosts
            - ssl
